version: '3'

services:
  web:
    container_name: node
    build: .
    ports:
      - "3500:3500"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
      
  db:
    image: postgres:13
    container_name: db
    restart: always
    ports:
      - '5433:5432'
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: node-db
